FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

WORKDIR /savaglow

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /savaglow
ENV ASPNETCORE_URLS=http://*:5000
COPY --from=build /savaglow/out .
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
CMD /wait && dotnet Savaglow.dll

